---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: doc

platforms:
  - name: ubuntu-14.04
  # - name: centos-7.2 - Ubuntu has a package for bamtools, centos does not

suites:
  - name: default
    run_list:
      - recipe[sga::default]
    attributes:
