name 'sga'
maintainer 'Eagle Genomics Ltd'
maintainer_email 'chef@eaglegenomics.com'
license 'apachev2'
description 'Installs/Configures sga'
long_description 'Installs/Configures sga'
source_url 'https://github.com/EagleGenomics-cookbooks/sga'
issues_url 'https://github.com/EagleGenomics-cookbooks/sga/issues'
version '1.0.0'

depends 'build-essential'
depends 'apt'
depends 'git'
depends 'poise-python'
